
# Para enviar email por gmail from my enviroment de production
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Logs detallados de Spring Mail y JavaMail
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG
logging.level.com.sun.mail.smtp=DEBUG

