
# Para enviar email por gmail from my enviroment de desarrollo
# spring.profiles.active=dev no puse esto en el run de intellij colocando esto: -Dspring.profiles.active=dev
spring.mail.username=fgocam@gmail.com
spring.mail.password=dlfa nqwc nick ignr


