spring.application.name=academia

# Para versional el file json
app.json.version=2


# Para enviar email por gmail from my application
spring.profiles.active=dev
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fgocam@gmail.com
spring.mail.password=dlfa nqwc nick ignr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

